2016/17:
  boxing_day: 26
  finished_in_top_4_last_season:
  - Leicester
  - Arsenal
  - Spurs
  - Man City
  is_in_ucl_this_season:
  - Leicester
  - Arsenal
  - Spurs
  - Man City
  is_in_uel_this_season:
  - Man Utd
  - Southampton
  promoted_teams:
  - Burnley
  - Middlesbrough
  - Hull
  reigning_champion: Leicester
  traditional_top_6:
  - Man Utd
  - Liverpool
  - Arsenal
  - Chelsea
  - Man City
  - Spurs
  was_in_ucl_last_season:
  - Man City
  - Man Utd
  - Arsenal
  - Chelsea
  was_in_uel_last_season:
  - Liverpool
  - Spurs
  won_carabao_cup_last_season: Man City
  won_fa_cup_last_season: Man Utd
2017/18:
  boxing_day: 26
  finished_in_top_4_last_season:
  - Chelsea
  - Spurs
  - Man City
  - Liverpool
  is_in_ucl_this_season:
  - Chelsea
  - Spurs
  - Man City
  - Liverpool
  - Man Utd
  is_in_uel_this_season:
  - Everton
  - Arsenal
  promoted_teams:
  - Huddersfield
  - Newcastle
  - Brighton
  reigning_champion: Chelsea
  traditional_top_6:
  - Man Utd
  - Liverpool
  - Arsenal
  - Chelsea
  - Man City
  - Spurs
  was_in_ucl_last_season:
  - Leicester
  - Arsenal
  - Spurs
  - Man City
  was_in_uel_last_season:
  - Man Utd
  - Southampton
  won_carabao_cup_last_season: Man Utd
  won_fa_cup_last_season: Arsenal
2018/19:
  boxing_day: 26
  finished_in_top_4_last_season:
  - Man City
  - Man Utd
  - Spurs
  - Liverpool
  is_in_ucl_this_season:
  - Man City
  - Man Utd
  - Spurs
  - Liverpool
  is_in_uel_this_season:
  - Arsenal
  - Chelsea
  promoted_teams:
  - Wolves
  - Cardiff
  - Fulham
  reigning_champion: Man City
  traditional_top_6:
  - Man Utd
  - Liverpool
  - Arsenal
  - Chelsea
  - Man City
  - Spurs
  was_in_ucl_last_season:
  - Chelsea
  - Spurs
  - Man City
  - Liverpool
  - Man Utd
  was_in_uel_last_season:
  - Everton
  - Arsenal
  won_carabao_cup_last_season: Man City
  won_fa_cup_last_season: Chelsea
2019/20:
  boxing_day: 26
  finished_in_top_4_last_season:
  - Man City
  - Liverpool
  - Chelsea
  - Spurs
  is_in_ucl_this_season:
  - Man City
  - Liverpool
  - Chelsea
  - Spurs
  is_in_uel_this_season:
  - Arsenal
  - Man Utd
  promoted_teams:
  - Norwich
  - Sheffield Utd
  - Aston Villa
  reigning_champion: Man City
  traditional_top_6:
  - Man Utd
  - Liverpool
  - Arsenal
  - Chelsea
  - Man City
  - Spurs
  was_in_ucl_last_season:
  - Man City
  - Man Utd
  - Spurs
  - Liverpool
  was_in_uel_last_season:
  - Arsenal
  - Chelsea
  won_carabao_cup_last_season: Man City
  won_fa_cup_last_season: Man City
2020/21:
  boxing_day: 26
  finished_in_top_4_last_season:
  - Liverpool
  - Man City
  - Man Utd
  - Chelsea
  is_in_ucl_this_season:
  - Liverpool
  - Man City
  - Man Utd
  - Chelsea
  is_in_uel_this_season:
  - Arsenal
  - Spurs
  - Leicester
  promoted_teams:
  - West Brom
  - Fulham
  - Leeds
  reigning_champion: Liverpool
  traditional_top_6:
  - Man Utd
  - Liverpool
  - Arsenal
  - Chelsea
  - Man City
  - Spurs
  was_in_ucl_last_season:
  - Man City
  - Liverpool
  - Chelsea
  - Spurs
  was_in_uel_last_season:
  - Arsenal
  - Man Utd
  won_carabao_cup_last_season: Man City
  won_fa_cup_last_season: Arsenal
2021/22:
  boxing_day: 26
  finished_in_top_4_last_season:
  - Man City
  - Man Utd
  - Liverpool
  - Chelsea
  is_in_ucl_this_season:
  - Man City
  - Man Utd
  - Liverpool
  - Chelsea
  is_in_uel_this_season:
  - West Ham
  - Leicester
  promoted_teams:
  - Watford
  - Norwich
  - Brentford
  reigning_champion: Man City
  traditional_top_6:
  - Man Utd
  - Liverpool
  - Arsenal
  - Chelsea
  - Man City
  - Spurs
  was_in_ucl_last_season:
  - Liverpool
  - Man City
  - Man Utd
  - Chelsea
  was_in_uel_last_season:
  - Arsenal
  - Spurs
  - Leicester
  won_carabao_cup_last_season: Man City
  won_fa_cup_last_season: Leicester
2022/23:
  boxing_day: 26
  finished_in_top_4_last_season:
  - Man City
  - Liverpool
  - Chelsea
  - Spurs
  is_in_ucl_this_season:
  - Man City
  - Liverpool
  - Chelsea
  - Spurs
  is_in_uel_this_season:
  - Arsenal
  - Man Utd
  promoted_teams:
  - Fulham
  - Bournemouth
  - Nott\'m Forest 
  reigning_champion: Man City
  traditional_top_6:
  - Man Utd
  - Liverpool
  - Arsenal
  - Chelsea
  - Man City
  - Spurs
  was_in_ucl_last_season:
  - Liverpool
  - Man City
  - Man Utd
  - Chelsea
  was_in_uel_last_season:
  - West Ham
  - Leicester
  won_carabao_cup_last_season: Liverpool
  won_fa_cup_last_season: Liverpool
credentials:
  driver_path: /Users/kzeynalzade/Downloads/.wdm/drivers/chromedriver/mac64/105.0.5195/chromedriver
  target_url: https://www.premierleague.com
features:
  batch_model_features:
  - match_week
  - month
  - day
  - weekday
  - h_position
  - a_position
  - total_n_matches_played_h
  - total_n_matches_played_a
  - total_max_points_h
  - total_max_points_a
  - total_points_h_cum
  - total_points_a_cum
  - total_points_dropped_h
  - total_points_dropped_a
  - total_goals_scored_h
  - total_goals_scored_a
  - total_goals_conceded_h
  - total_goals_conceded_a
  - total_avg_possession_h
  - total_avg_possession_a
  - total_avg_possession_last_3_h
  - total_avg_possession_last_3_a
  - total_avg_possession_last_5_h
  - total_avg_possession_last_5_a
  - total_avg_shots_on_target_h
  - total_avg_shots_on_target_a
  - total_avg_shots_on_target_last_3_h
  - total_avg_shots_on_target_last_3_a
  - total_avg_shots_on_target_last_5_h
  - total_avg_shots_on_target_last_5_a
  - total_avg_shots_h
  - total_avg_shots_a
  - total_avg_shots_last_3_h
  - total_avg_shots_last_3_a
  - total_avg_shots_last_5_h
  - total_avg_shots_last_5_a
  - total_avg_touches_h
  - total_avg_touches_a
  - total_avg_touches_last_3_h
  - total_avg_touches_last_3_a
  - total_avg_touches_last_5_h
  - total_avg_touches_last_5_a
  - total_avg_passes_h
  - total_avg_passes_a
  - total_avg_passes_last_3_h
  - total_avg_passes_last_3_a
  - total_avg_passes_last_5_h
  - total_avg_passes_last_5_a
  - total_avg_tackles_h
  - total_avg_tackles_a
  - total_avg_tackles_last_3_h
  - total_avg_tackles_last_3_a
  - total_avg_tackles_last_5_h
  - total_avg_tackles_last_5_a
  - total_avg_clearances_h
  - total_avg_clearances_a
  - total_avg_clearances_last_3_h
  - total_avg_clearances_last_3_a
  - total_avg_clearances_last_5_h
  - total_avg_clearances_last_5_a
  - total_avg_corners_h
  - total_avg_corners_a
  - total_avg_corners_last_3_h
  - total_avg_corners_last_3_a
  - total_avg_corners_last_5_h
  - total_avg_corners_last_5_a
  - total_avg_offsides_h
  - total_avg_offsides_a
  - total_avg_offsides_last_3_h
  - total_avg_offsides_last_3_a
  - total_avg_offsides_last_5_h
  - total_avg_offsides_last_5_a
  - total_avg_yellow_cards_h
  - total_avg_yellow_cards_a
  - total_avg_yellow_cards_last_3_h
  - total_avg_yellow_cards_last_3_a
  - total_avg_yellow_cards_last_5_h
  - total_avg_yellow_cards_last_5_a
  - total_avg_fouls_conceded_h
  - total_avg_fouls_conceded_a
  - total_avg_fouls_conceded_last_3_h
  - total_avg_fouls_conceded_last_3_a
  - total_avg_fouls_conceded_last_5_h
  - total_avg_fouls_conceded_last_5_a
  - n_matches_played_h
  - n_matches_played_a
  - max_points_h
  - max_points_a
  - points_h_cum
  - points_a_cum
  - points_dropped_h
  - points_dropped_a
  - goals_scored_h_cum
  - goals_scored_a_cum
  - goals_conceded_h_cum
  - goals_conceded_a_cum
  - avg_possession_h
  - avg_possession_a
  - avg_possession_last_3_h
  - avg_possession_last_3_a
  - avg_possession_last_5_h
  - avg_possession_last_5_a
  - avg_shots_on_target_h
  - avg_shots_on_target_a
  - avg_shots_on_target_last_3_h
  - avg_shots_on_target_last_3_a
  - avg_shots_on_target_last_5_h
  - avg_shots_on_target_last_5_a
  - avg_shots_h
  - avg_shots_a
  - avg_shots_last_3_h
  - avg_shots_last_3_a
  - avg_shots_last_5_h
  - avg_shots_last_5_a
  - avg_touches_h
  - avg_touches_a
  - avg_touches_last_3_h
  - avg_touches_last_3_a
  - avg_touches_last_5_h
  - avg_touches_last_5_a
  - avg_passes_h
  - avg_passes_a
  - avg_passes_last_3_h
  - avg_passes_last_3_a
  - avg_passes_last_5_h
  - avg_passes_last_5_a
  - avg_tackles_h
  - avg_tackles_a
  - avg_tackles_last_3_h
  - avg_tackles_last_3_a
  - avg_tackles_last_5_h
  - avg_tackles_last_5_a
  - avg_clearances_h
  - avg_clearances_a
  - avg_clearances_last_3_h
  - avg_clearances_last_3_a
  - avg_clearances_last_5_h
  - avg_clearances_last_5_a
  - avg_corners_h
  - avg_corners_a
  - avg_corners_last_3_h
  - avg_corners_last_3_a
  - avg_corners_last_5_h
  - avg_corners_last_5_a
  - avg_offsides_h
  - avg_offsides_a
  - avg_offsides_last_3_h
  - avg_offsides_last_3_a
  - avg_offsides_last_5_h
  - avg_offsides_last_5_a
  - avg_yellow_cards_h
  - avg_yellow_cards_a
  - avg_yellow_cards_last_3_h
  - avg_yellow_cards_last_3_a
  - avg_yellow_cards_last_5_h
  - avg_yellow_cards_last_5_a
  - avg_fouls_conceded_h
  - avg_fouls_conceded_a
  - avg_fouls_conceded_last_3_h
  - avg_fouls_conceded_last_3_a
  - avg_fouls_conceded_last_5_h
  - avg_fouls_conceded_last_5_a
  - is_boxing_day
  - finished_top_4_last_season_h
  - finished_top_4_last_season_a
  - won_carabao_cup_last_season_h
  - won_carabao_cup_last_season_a
  - won_fa_cup_last_season_h
  - won_fa_cup_last_season_a
  - won_epl_last_season_h
  - won_epl_last_season_a
  - was_in_ucl_last_season_h
  - was_in_ucl_last_season_a
  - was_in_uel_last_season_h
  - was_in_uel_last_season_a
  - is_in_ucl_this_season_h
  - is_in_ucl_this_season_a
  - is_in_uel_this_season_h
  - is_in_uel_this_season_a
  - traditional_top_6_h
  - traditional_top_6_a
  - newly_promoted_h
  - newly_promoted_a
  - total_goal_difference_h
  - total_goal_difference_a
  - goal_difference_h
  - goal_difference_a
  - positive_total_goal_difference_h
  - positive_total_goal_difference_a
  - positive_goal_difference_h
  - positive_goal_difference_a
  - is_derby
models_paths:
  draw_model_path: draw_model.pickle
  loss_model_path: loss_model.pickle
  win_model_path: win_model.pickle
shadow_models_paths:
  shadow_draw_model_path: shadow_draw_model.pickle
  shadow_loss_model_path: shadow_loss_model.pickle
  shadow_win_model_path: shadow_win_model.pickle
target:
  draw_model: draw
  loss_model: away_win
  win_model: home_win
test_split:
  test_season: 2021/22
current_season:
  2022/23